---
title: Rasik Kane
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
permalink: none
gem:
- jekyll-paginate
- jekyll-gists
- gist
- jekyll-sitemap
- jekyll-seo-tag
- jemoji
tagline: Rasik Kane blog
description: My Blog about learning- Unlearning 
url: http://RasikKane.github.io
baseurl: "/"
imageurl: "/"
author:
  name: Rasik Kane
  url: https://twitter.com/KaneRasik
paginate: 5
github_username: RasikKane
linkedin_username: rasikkane
twitter_username: KaneRasik
email: rasik.kane@gmail.com
version: 1.0.3
disqus:
  shortname: RasikKane-github-io
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-paginate
- jemoji
github:
  repo: https://github.com/RasikKane
